### ISSUE TITLE
Kits having things removes

### ISSUE THREAD

**Issue by socomdBandit** [SOCOMD/MODS#28] opened 2021-10-15 12:10 UTC
**Description:**

-  Various kits have saving and loading issues, grabbing a kit from Qstore and personalising doesn't affect this, when loading a saved kit it can be missing its entire uniform inventory, grabbing a new kit personalising and saving again does not fix. Experienced mainly by pilots and possibly other kits 
**Steps to reproduce:**

-   Load a pilot kit, personalise, save, loading will result in an empty/almost empty uniform

**Additional information:**

-   N/A

**Comment by socomdBandit** [comment] 2021-11-22 00:45
updated to better reflect the issue

**Comment by SpectreOfRohan** [comment] 2022-01-13 10:23
This is a "works for me" / "can't personally reproduce" issue. People having the issue should try deleting @socomd mods and redownloading. Then monitor if they have the issue again.

**Comment by Slatery** [comment] 2022-02-20 11:19
will close this after next Friday op if all things go well

**Closed** 2022-03-05 04:59 UTC
Labels: bug, area:loadouts, status:not started
